name: Ubuntu Build's
on:
  push:
    branches: 
      - master
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install Depenancies
        run: |
          sudo apt update
          sudo apt install libsystemd-dev libspdlog-dev
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Generate Build Files
        env:
          CC: gcc-8
          CXX: g++-8
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        env:
          CC: gcc-8
          CXX: g++-8
        run: |
          cd build
          make -j 2
      - name: Test
        env:
          CC: gcc-8
          CXX: g++-8
        run: |
          cd build
          make test
